name: Deploy to FTP

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies and build assets
      run: |
        composer install
        npm install
        npm run build

    # - name: Deploy config to FTP
    #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: ./config/
    #     server-dir: /webcup24/config/

    # - name: Deploy src to FTP
    #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: ./src/
    #     server-dir: /webcup24/src/

    # - name: Deploy public to FTP
    #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: ./public/
    #     server-dir: /webcup24/public/

    # - name: Deploy templates to FTP
    #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: ./templates/
    #     server-dir: /webcup24/templates/

    # - name: Deploy node_modules to FTP
    #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: ./node_modules/
    #     server-dir: /webcup24/node_modules/

    # - name: Deploy vendor to FTP
    #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: ./vendor/
    #     server-dir: /webcup24/vendor/

    # - name: Push .env file to server
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     source: .env
    #     target: /webcup24/.env
